version: "3.9"
services:
  backend:
    image: kawwik/payment-service
    ports:
      - 8080:80
    networks:
      - backend
    environment:
      SPRING__DATA__MONGODB__URI: mongodb://mongo:27017/
      SPRING__KAFKA__BOOTSTRAP-SERVERS: "kafka:29092"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    networks:
      - kafka
      - backend
    environment:
      KAFKA_CREATE_TOPICS: "cinephilia.payments.movie-purchased:1:1"
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka
    ports:
      - "9000:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true

  mongo:
    build:
      context: mongoDb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

volumes:
  mongo_data: { }

networks:
  kafka:
  backend: