# MongoDB properties
spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      movie-purchased: cinephilia.payments.movie-purchased
    bootstrap-servers: "localhost:29092"

# Tiny event sourcing library properties
event:
  sourcing:
    auto-scan-enabled: true
    scan-package: com.cinephilia.payment
    snapshot-frequency: 100
