# MongoDB properties
# swagger-ui custom path

springdoc.swagger-ui.path: "/payments/api/v1/swagger"
springdoc.api-docs.path: "/payments/api/v1/swagger-docs"

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      movie-purchased: cinephilia.payments.movie-purchased
    bootstrap-servers: "kafka-cluster-kafka-bootstrap.strimzi.svc.cluster.local:9092"

# Tiny event sourcing library properties
event:
  sourcing:
    auto-scan-enabled: true
    scan-package: com.cinephilia.payment
    snapshot-frequency: 100

management:
  metrics:
    tags:
      application: payments
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

otel:
  propagators: tracecontext
  resource:
    attributes:
      deployment:
      environment: prod
      service:
        name: payments
        namespace: com.cinephilia
  metrics:
    exporter: none
  logs:
    exporter: none
